name: Full CI CD Workflow

on:
  workflow_dispatch:
  
jobs:
  call-ci-workflow:
    uses: ./.github/workflows/IntegrationTest.yml
    secrets: inherit
  call-deployfunctions-apps-workflow:
    needs: call-ci-workflow
    uses: ./.github/workflows/DeployFunctionsApps.yml
    secrets: inherit
  delay:
    runs-on: ubuntu-latest
    needs: call-deployfunctions-apps-workflow
    steps:
    - name: Sleep for 60 seconds to let the Functions Apps finished deployment and start
      run: sleep 60
      shell: bash
  call-test-deployed-functions-apps-workflow:
    needs: delay
    uses: ./.github/workflows/FunctionsAppsIntegrationTest.yml
    secrets: inherit
    
