name: Cloud Deployed Function App Integration Tests

on:
  workflow_dispatch:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        shell: bash
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Find functions apps urls 
      run: | 
          az config set extension.use_dynamic_install=yes_without_prompt
          export AccoountManagerKey=$(az functionapp keys list --resource-group "bms-func-app-rg" --name master-bms-accountmanager --query functionKeys.default | tr -d '"')
          export negotiateKey=$(az functionapp keys list --resource-group "bms-func-app-rg" --name master-bms-notificationmanager --query functionKeys.default | tr -d '"')
          echo "ACCOUNT_MANAGER_URL=https://master-bms-accountmanager.azurewebsites.net/api" >> $GITHUB_ENV
          echo "BMS_SIGNALR_URL=https://master-bms-notificationmanager.azurewebsites.net/api"  >> $GITHUB_ENV
          echo "ACCOUNTMANAGER_FUNCTION_KEY=$AccoountManagerKey" >> $GITHUB_ENV
          echo "NEGOTIATE_FUNCTION_KEY=$negotiateKey" >> $GITHUB_ENV
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
     - name: Test
       run: |
         dotnet build --configuration Release Tests/BMS.Tests.IntegrationTests/BMS.Tests.IntegrationTests.csproj 
     - name: Test
      run: |
        echo testing function app deployment 
        echo with manager url: ${{ env.ACCOUNT_MANAGER_URL }}
        echo and notification url: ${{ env.BMS_SIGNALR_URL }}
        dotnet test --no-build --verbosity normal --configuration Release Tests/BMS.Tests.IntegrationTests/BMS.Tests.IntegrationTests.csproj
    
