name: Functions App Integration Tests

on:
  workflow_dispatch:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        shell: bash
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Find functions apps urls 
      run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          export AccoountManagerUrl=$(az containerapp show --resource-group "bmsd-cont-app-rg" --name accountmanager --query properties.configuration.ingress.fqdn | tr -d '"')
          export SignalRUrl=$(az containerapp show --resource-group "bmsd-cont-app-rg" --name notificationmanager --query properties.configuration.ingress.fqdn | tr -d '"')
          echo "Account Manager Url: $AccoountManagerUrl"
          echo "Notification Manager Url: $SignalRUrl"
          echo "ACCOUNT_MANAGER_URL=https://$AccoountManagerUrl" >> $GITHUB_ENV
          echo "BMSD_SIGNALR_URL=https://$SignalRUrl"  >> $GITHUB_ENV
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
    - name: Test
      #env:
      #  BMSD_SIGNALR_URL: ${{ env.NotificationManagerFQDN }}
      #  ACCOUNT_MANAGER_URL: ${{ env.AccountManagerFQDN }}
      run: |
        echo testing function app deployment 
        echo with manager url: ${{ env.ACCOUNT_MANAGER_URL }}
        echo and notification url: ${{ env.BMSD_SIGNALR_URL }}
        dotnet test --verbosity normal --configuration Release Tests/MSD.Tests.IntegrationTests/MSD.Tests.IntegrationTests.csproj
    
