name: Build anf integration tests

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths-ignore:
    - '.github/**'
    - 'infra/**'
   
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths-ignore:
    - '.github/**'
    - 'infra/**'
    
env:
  CosmosDbConnectionString: ${{ secrets.BMS_COSMOSDB_CONNECTION_STRING }}
  SignalRConnectionString: ${{ secrets.BMS_SIGNALR_CONNECTION_STRING }}
 
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
    - name: Docker Compose Up
      run: docker compose -f docker-compose.yml up -d
    - name: Restore dependencies
      run: dotnet restore BMS.sln
    - name: Build
      run: dotnet build --no-restore BMS.sln
    - name: Docker ps
      run: docker ps
    - name: Run all functions for the test
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-4
        cd Accessors/BMS.Accessors.CheckingAccount
        func start &
        cd ../../Accessors/BMS.Accessors.UserInfo
        func start &
        cd ../../Engines/LiabilityValidator
        func start &
        cd ../../Managers/BMS.Managers.Notification
        func start &
        cd ../../Managers/BMS.Managers.Account
        func start &
        cd ../..
        sleep 20
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Debug Tests/BMS.Tests.IntegrationTests/BMS.Tests.IntegrationTests.csproj
    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v1
    - name: Stop containers
      if: always()
      run: docker compose down
